# Generated by Django 5.0 on 2023-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('access_code', models.TextField(default='1234', max_length=4)),
                ('option_a', models.CharField(default='', max_length=30)),
                ('option_b', models.CharField(default='', max_length=30)),
                ('option_c', models.CharField(default='', max_length=30)),
                ('option_d', models.CharField(default='', max_length=30)),
                ('option_a_count', models.IntegerField(default=0)),
                ('option_b_count', models.IntegerField(default=0)),
                ('option_c_count', models.IntegerField(default=0)),
                ('option_d_count', models.IntegerField(default=0)),
            ],
        ),
    ]
