# Generated by Django 5.0 on 2023-12-16 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
    ]
