# Generated by Django 5.0 on 2023-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20231216_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='access_code',
            field=models.TextField(default=''),
        ),
    ]
