# Generated by Django 5.0 on 2023-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_poll_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='access_code',
            field=models.TextField(max_length=255),
        ),
    ]
