# Generated by Django 5.0 on 2023-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_a_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_b_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_c_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_d_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
