# Generated by Django 5.0 on 2023-12-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_poll_option_a_count_alter_poll_option_b_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='access_code',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
